version: '3.1'

services:

  mongo:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWD}
    volumes: 
      - ./database/mongodbdata:/data/db
  
  spring:
    image: georgiydemo/spring-mychat-server
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      MONGO_DB: ${MONGO_DB}
      MONGO_URL: ${MONGO_URL}
    depends_on:
      - mongo
